# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2076f1b487e46ef981fece4cf3cdc167d5d799c333b56296742fbaca159ccfbfa64927105eae2e19e5f3c30d81b485e71df90279df44f604fb7196a7981ec21

test:
  secret_key_base: c0b1c0425b303971c043e3a02acff97921c000d6de6da417e620bd776f2695617345e9502685ebc17be18df80977f44a71adea06eefb4c6ff1cc9be2042edd44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
